# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79c044085f060d6592a5a0d7c4e170497d76e9485dbe0e0520526df0d68fbe954d8ad2ab2cb4ea58143acf489099e6ad596807c7702d8ee0721ab7673eadca2b

test:
  secret_key_base: c78f168a0980f2aa9147e8ca374eecce72b5127b5a61beb8dc356f41f52403124abee8913de376e2d24e47979e617b7e0e5a8b35dc9375c0a0d5428ffdf5cd0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
